### ISSUE TITLE
c chapter doesn't work on SERP

### ISSUE THREAD

**Issue by volosovich** [infokiller/web-search-navigator#173]
When I use your addons on the search result page (SERP) doesn't work c key. This key works when I switch off your addons.
Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by infokiller** [comment]
I can't reproduce, do you mean typing c in the search box?
Can you screenshot the keybindings you have set in your extension options?

**Comment by volosovich** [comment]
yes.
Steps to reproduce:
1 search something on google
2 on the search result page try to type c chapter
macOS 10.15.5

![111111](https://user-images.githubusercontent.com/1928765/87340919-6b36d580-c551-11ea-8b59-18ebd6db4ce2.gif)
![image](https://user-images.githubusercontent.com/1928765/87341030-96b9c000-c551-11ea-814e-a60c618ef800.png)
![image](https://user-images.githubusercontent.com/1928765/87341070-a3d6af00-c551-11ea-8736-1b58edc27f90.png)

**Comment by infokiller** [comment]
I think I know what the issue is, and I just released a new version (0.4.9) which should fix it, though it may take a few hours for the update to take effect (you can check in `chrome://extensions` the extension version).
You can also try to go to the options and click "save" or "restore to defaults" which should fix it.

**Comment by volosovich** [comment]
awesome, fixed
