### ISSUE TITLE
Edge extension is old 0.4.13

### ISSUE THREAD

**Issue by Anteus** [infokiller/web-search-navigator#264]
Version 0.4.13 on Microsofts store
https://microsoftedge.microsoft.com/addons/detail/web-search-navigator/inkjbmhmeghalgpacijccmbmbclkjgop

Works fine to install the Chrome one though.

**Comment by infokiller** [comment]
Thanks for reporting. @rik-smeets can you please release a new version for Edge?

**Comment by rik-smeets** [comment]
I have just submitted the newest version for publication in the Microsoft Store. Should be done within 7 days from now.

I wasn't aware that newer versions were published since I didn't see any new release here on GitHub. The latest one published here is still [0.4.13](https://github.com/infokiller/web-search-navigator/releases). I don't use Google Chrome anymore so I didn't notice the extension was being updated in the store there either.

**Comment by infokiller** [comment]
Thanks! Yeah, I didn't add new releases to Github, though I do use git tags that show up there.

**Comment by infokiller** [comment]
Looks like it was updated, closing

**Comment by Anteus** [comment]
It happened again

**Comment by infokiller** [comment]
@Anteus can you install the one from the Chrome web store?
@rik-smeets can you please upload a new version?

**Comment by Anteus** [comment]
> @Anteus can you install the one from the Chrome web store?
> 
> @rik-smeets can you please upload a new version?

Thanks I already swapped over to try it on Brave

**Comment by rik-smeets** [comment]
@infokiller I tried uploading a new version, but the manifest version in use (2) is no longer supported for Microsoft Edge. It has to be 3. 

I'm not sure when I'll get around to updating that, is it something you're already planning to do in the near future?

**Comment by infokiller** [comment]
Yes, I plan to do it, you can track #301

**Comment by rik-smeets** [comment]
Alright, thanks. Will track that. Will upload a new version whenever it hits a.s.a.p.
