### ISSUE TITLE
Add option for "Time" (default "t")

### ISSUE THREAD

**Issue by afilp** [infokiller/web-search-navigator#30]
Restricting search to time is something many users do (especially for news, etc.).

May I propose a quick shortcut?

1. Add an option for "Time" (default "t")

2. This opens this dialog (if possible)

![image](https://user-images.githubusercontent.com/7850073/32881069-96c855de-cab8-11e7-9ed8-4cafc97fce7d.png)

3. The  focus should go there (this is important), so that with the TAB the user can navigate the options and press enter (or ESC to quit).
Even better, we could have the proposed letter shortcuts (see screenshot) for fast selection of the time period.

What do you think?

**Comment by infokiller** [comment]
Thanks, that looks like a useful feature. Personally, I don't think I'll get to implementing it soon, but feel free to send a PR.

**Comment by mancze** [comment]
I like the bare idea but for me the issue seems is too specific limiting its focus to only certain functionality and not interpreting the google search as a whole. One has to ask how frequently is this particular feature used by users? It is worth reserving such lucrative shortcut for this command? Wouldn't be fixing classical keyboard-based ui navigation good enough?

Personally I would rather see an general way how to navigate via/focus search tabs (all, videos, images, news, settings, tools,...) effectively. Then achieving described goal would be as easy as:

1. Use shortcut to focus "Tools" tab.
2. Press Enter (time input gets focused).
3. Press Enter (time input gets expanded and focused).
4. Pick your option using Tab key.

The first point needs to be implemented. The second and third comes out of the box. The fourth needs improvements.

ad 1:
Currently the left/right arrow is reserved for navigating to previous/next page. I don't use that. I traverse search results sequentially using up/down and when I hit the last of the search results next item to focus should be arrow pointing to the next page. Navigating to previous page is as simple as using browser's back button. No need for another shortcut for it.

ad 4:
Tab key works, but it would be handful having our shortcut to next/previous result (up/down arrows) mapped here. Also Escape key does not work here - it seems the Google ditched the support for keyboard users at all...

**Comment by afilp** [comment]
I like what @mancze proposes. 

However, I tried to press enter while "Tools" is focused and instead of it opening the 1st result opened (expected, as "Enter" opens the 1st "selected" result).

**Comment by afilp** [comment]
I have a suggestion here (this uses shortcuts):

If the "sequences" plugin is used (https://github.com/cmawhorter/keymaster-sequences.js), then the "Time" use case can be handled easily:

```
key.sequence('t 2', function(evt, handler, sequence) {
  console.log('You pressed t then 2, so "Past 24 hours" will be selected inside this handler');
  // code to select the "Past 24 hours" here
});
```

**Comment by tkroll** [comment]
This was added in recent update

**Comment by afilp** [comment]
@tkroll This is nice! CTRL-SHIFT-W closes the tab though, is this a proper shortcut?

**Comment by afilp** [comment]
Also, I cannot fine the extension in Chrome Web Store anymore, how can we update it?

https://chrome.google.com/webstore/search/%22google%20search%20navigator%22?_category=extensions

**Comment by infokiller** [comment]
Waiting for a Google review, see #60

**Comment by tkroll** [comment]
@afilp Oh crap. Mac user here. Can you get my some good Windows alternatives? I'll also add these to the Options menu.

**Comment by afilp** [comment]
@tkroll I am afraid that most of these shortcuts are used for something else in Windows, so I would not go for the "CTRL-SHIFT-..." combinations.

Maybe use a "gmail style sequence" by importing the `mousetrap` package?
https://github.com/ccampbell/mousetrap

So you could have: 
"t a"
"t h"
"t d"
... etc.

**Comment by tkroll** [comment]
@aflip: Mousetrap look pretty cool. The new functions are now in Options screen.
@infokiller: Should I do a fork with Mousetrap to test?

**Comment by infokiller** [comment]
@tkroll yes that sounds good

**Comment by tkroll** [comment]
Removed keymaster and added mousetrap (https://github.com/ccampbell/mousetrap).
Since mousetrap binds with an array of strings instead of a string, I changed the options to handle that. The options page still works the same way.

I used Gmail-style, double-keys for the search/time settings. See options screen.

Please take a look and comment:
https://github.com/tkroll/google-search-navigator/tree/search-tools

**Comment by infokiller** [comment]
Just tried it, looks pretty good. I also took a quick look at the commit in your branch, a minor comment I have: please use the un-minified name of mousetrap. The minified version will be generated with the same name using `yarn build --production` (this is how it's currently done for keymaster as well).

Thanks!

**Comment by tkroll** [comment]
@infokiller Noted and corrected. Update pushed.

**Comment by afilp** [comment]
@infokiller @tkroll Is this merged to master? I think not, based on that commit:

https://github.com/tkroll/google-search-navigator/commit/a64557a1994a4714a8e9b9a0da690b928112a576

Windows users (like me) need this, because `Ctrl+Shift+w` closes all browser tabs, etc.

**Comment by tkroll** [comment]
Yeah, I did it wrong. Will have to redo from current master when I have time.

**Comment by afilp** [comment]
@tkroll May I help somehow? I think you are very close, what was the problem and was not merged/released? Thanks!

**Comment by tkroll** [comment]
I wanted to wait until you moved to typescript actually. Also found a weird bug that it focuses on the next button and scrolls down. Do you see that behavior?

**Comment by infokiller** [comment]
@tkroll what version are you using?
This should have been fixed in the chrome web store version.

**Comment by tkroll** [comment]
Realized it's my unmerged version. I'll handle it.

**Comment by afilp** [comment]
@tkroll Hi! Can your PR make it to the actual product? The current shortcuts are still unusable in Windows but yours are. Thanks!

Also, may I recommend that we also add "SHIFT-downarrow" and "SHIFT-uparrow" to navigate through the "More results from..." section?

![image](https://user-images.githubusercontent.com/7850073/49339201-132ab400-f637-11e8-80ad-e3e6ee3b9ae9.png)

**Comment by mancze** [comment]
@afilp With #94 it is possible to navigate to subresults and "more results from..." or whatever using the default browser focus shortcuts - `tab` key and `shift+tab`.

**Comment by tkroll** [comment]
@afilp I'm back. Sorry for the delay. I'll take a look.

**Comment by tkroll** [comment]
@afilp @infokiller New PR ready to go.
