### ISSUE TITLE
Improve docs for adding a search engine

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#300]
> @bulutfatih I wanted to take this opportunity to get your feedback as a first time contributor: how was the experience of adding a new search engine? were the docs in the README ok?
> If there's anything that can be improved, please let me know.
> 
> Thanks

It took time to understand the logic, how things work. Maybe we should add more comments to important functions or improve the documentation in the `search_engines.js` file.
Targeting the highlight element and the container was a bit difficult. I figured it out after a few tries.
Reference commit wasn't clear, I read the code of Google and Startpage.
Need better eslint and prettier configurations.
README was good.

_Originally posted by @bulutfatih in https://github.com/infokiller/web-search-navigator/issues/292#issuecomment-913196707_

**Comment by infokiller** [comment]
Thanks for the feedback @bulutfatih 
A few follow-up questions:
- Did you read the documentation at the top of https://github.com/infokiller/web-search-navigator/blob/master/src/search_engines.js? if so, why was it lacking?
- Was targeting the highlight/container elements difficult because the documentation is unclear?
- What is missing in the eslint and prettier configs?

**Comment by bulutfatih** [comment]
- I read it, but I don't remember now why I thought so. Maybe it was difficult not because of documentation but html structure and lack of selectors in search engine.
- Prettier doesn't work for me. It gives this error when I try to format. `Extension 'esbenp.prettier-vscode' is configured as formatter but not available. Select a different default formatter to continue.`
Also, it would be nice to have a script for linting.

**Comment by infokiller** [comment]
I added an NPM script for linting. Seems that the error you get is related to VSCode, not sure what's wrong there, but I'll add VScode config as well
