### ISSUE TITLE
Navigating youtube results with playlists

### ISSUE THREAD

**Issue by nsrCodes** [infokiller/web-search-navigator#382]
If the results of a youtube query has playlists, I was expecting to be able to `ctrl` + `Enter` to open the playlist on a new tab and further navigate from there.

> Navigating when the playlist is opened works perfectly. 

![youtube-playlist-navigation](https://user-images.githubusercontent.com/57226514/169707351-c27b9265-7a74-4856-9af3-e1b8c3c779dc.gif)

**Comment by infokiller** [comment]
Thanks for reporting this issue!
I think I fixed in the current master version, if you can verify that would be great. As a reminder, follow [infokiller/web-search-navigator#building-for-development](https://github.com/infokiller/web-search-navigator#building-for-development) (if you cloned the repo previously, you will need to `git pull`).

**Comment by nsrCodes** [comment]
Yeah the latest master has this fixed for both chrome and firefox. Sorry for the redundant issue 😓

**Comment by infokiller** [comment]
Don't be sorry- I only fixed it after you reported it, so thanks!
I will probably make a new release in the next few days. I'll keep this issue open till then.

**Comment by infokiller** [comment]
Just released it to Chrome, will do it for Firefox as well

**Comment by infokiller** [comment]
Released for Firefox, closing
