### ISSUE TITLE
Support selecting and navigating to "sub-result links"

### ISSUE THREAD

**Issue by infokiller** [infokiller/web-search-navigator#43]
Selection can be done by using tab (via regular focus change in the browser), but when trying to navigate (via the extension keybindings), the navigation is done to the top level result instead of the sub-result.

Original email I got which triggered this issue:

> Hello,
> 
> I wanted to both thank you for your great work on this chrome plugin as well as provide some feedback.
> 
> When going through searches it is great if one wants the main result for each result box. But sometimes one result box has kind of like sub-result links at the bottom as seen below. This is especially comun when the result is from an online forum or reddit. The thing is when I use the arrow keys to move through results I can then use tab to move to the sub-results below it and but when I click enter the link it opens is the link with the arrow not the selection box. So there is no way of selecting a subresult with the keyboard shortcuts of the plugin. 
> 
> Below are 2 images the first one is with the main result selected (with the box). The second image shows the sub-result selected. But on both these images hitting the enter key opens the main result link indicated by the arrow. It would be helpful to change so that the squared link is the one selected.
> 
> ![image](https://user-images.githubusercontent.com/10516814/37857621-9d9b5154-2f0d-11e8-8471-bce5305adda0.png)
> sub-result "Some search engine tests" selected (reached by tabbing)
> 
> ![image](https://user-images.githubusercontent.com/10516814/37857624-a74075ea-2f0d-11e8-8262-11ed564b6579.png)
> 
> Aside from that, great job on the plugin I couldn't believe when google got rid of the instant search functionality that was so helpful. Keep up the good work.
> 
> Cheers

**Comment by mancze** [comment]
I'm not sure sub-result navigation was included in the original Instant Search keyboard navigation. If we're gonna implement this it should be configurable at least. Without it in the example shown above getting to the 3rd main result would require to activate next result shortcut 9 times. For me using plain old `tab` is good enough to reach sub-results.

**Comment by infokiller** [comment]
I don't think it was included in the Google implementation, and I agree that it's not a good idea to force users to navigate through these in their usual flow. Like you said we could introduce another opt-in option to navigate through sub-results, but my guess is that it won't be useful to that many users.
All that said, we should try to fix the current bug where using tab and then enter/space doesn't navigate to the sub-result (since the extension isn't "aware" of this navigation).

**Comment by mancze** [comment]
Ah, you are absolutely right. My thoughts drifted away from the original post.

**Comment by Tunscopi** [comment]
Hi @infokiller First, thank you for this brilliant extension! Been using one that was nice but this is better! Next, I also want to echo the sentiments for supporting sub-result navigation if this wouldn't be too much of a hassle. It sorta defeats the purpose when I navigate to sub results using TAB and then have to reach for my mouse to select those results( happens often ). Hitting TAB twice allows me to highlight the first sub-result and TAB afterwards highlights each successive next sub-result but I can only use the mouse to select any of them as opposed to enter/space.

**Comment by mancze** [comment]
To be honest, I forgot about this. I really should be possible to navigate to sub-results when focus is moved to them. I'm on it, will fix this soon. 

I'm thinking changing the logic of the navigation activation shortcuts (open, open in a new tab, open in a new background tab). The focused element (`document.activeElement`) should be clicked instead of the highlighted result (the result marked by the extension). I.e. The focused element has precedence over the highlighted result.

It can happen that highlighted result (the result marked by the extension) gets out-of-sync with the focused element. It is even possible to focus completely another result than the highlighted one using the `tab` key. I say the focused element has still precedence over highlighted result. 

(The experience might be improved if the highlighted result got updated when focus moved to another search result. But I'm not going to implement this for now.)

**Comment by Tunscopi** [comment]
Hi @mancze thanks for taking a look.
Given the user-focused element precedence over the extension result sounds like a good approach to resolving this.
