### ISSUE TITLE
Mouse middle click on a result should also focus it

### ISSUE THREAD

**Issue by VarunAgw** [infokiller/web-search-navigator#93]
If focus is on 1st result, and I middle click on 3rd result, focus should switch to it.

If I recall, original Google Instant used to have such behaviour

**Comment by infokiller** [comment]
It won't add much value to me personally (and I assume most of the extension users), since this extension should make it easier to only use the keyboard in Google search. Therefore, I probably won't implement it anytime soon, so will close the issue.
That said- the features sounds reasonable and I welcome PRs that add it, assuming they don't add much complexity to the extension.

**Comment by VarunAgw** [comment]
:'(

**Comment by mancze** [comment]
The feature which would make sense is "sync highlighted result with focused element". Meaning the highlighted result should be updated when focus goes to a link within container of one of the matched results. The highlighted result should not change when focused element is not related to any specific matched search result. Enabling the feature should be configurable, on by default. 

This way the highlight update wouldn't be tied to a mouse middle click but to any focus change event. This is what I mentioned in [#43](https://github.com/infokiller/web-search-navigator/issues/43#issuecomment-439682485).

Yet I'm also not going to implement this any time soon.
