### ISSUE TITLE
How to unfocus search box?

### ISSUE THREAD

**Issue by tedzhu** [infokiller/web-search-navigator#95]
There's a "Focus search box" command which is really useful.

But after using it, it seems there's no way to cleanly unfocus it.
1. press enter, do another search, focus first result
2. mouse click, or tab tab, press up down will somehow bring up the searchbox suggestions

Ideally, maybe press esc to unfocus search box and focus search result.

**Comment by mancze** [comment]
Confirmed, seems like a bug. In some previous version `esc` key worked to unfocus the search box as you suggest.

**Comment by mancze** [comment]
Had a minute to look onto this. I realized that previous functionality that input was blurred when hitting `esc` was feature out-of-the-box provided by google search itself. And I have a strong feeling that focus/blur logic was more complex. I think it was like:

1. Pressing "Focus search box" shortcut would focus search box and selected all text within. This also expanded the search suggestions below searchbox.
2. Pressing `esc` key would close the search suggestions, disable the selection and move the cursor to the end of the search term.
3. Finally pressing `esc` again would blur the search box.

What's worth noting is that only step 1 was handled by the extension, steps 2 and 3 were handled by google search itself. Also note that `esc` key was hardcoded to steps 2 and 3 and may not match the "focus search box" shortcut. Now the default behavior changed and it is not easy to blur the search box (it is possible by tabbing focus out of it).

I can fix it. But I believe preserving original workflow is desirable instead of having simple two-state focus/blur functionality. So I propose this mechanism: Everything is tied to the "focus search box" shortcut set in options. No more hardcoded `esc` key. When invoking this shortcut the states would be:

1. Search box is focused, all text selected, search suggestions opened up.
2. Search box is kept focused, search suggestions closed up, text deselected, cursor moved to the end of the search term appending the space after it when there is none (so another word can be typed right away).
3. Search box is blurred (and perhaps added space is removed, but it maybe does not really matter).

**Comment by infokiller** [comment]
I can't reproduce this- `esc` still gets me out of the search box to navigating results (though the suggestions stay open which is not ideal), and a single tab press gets me out of the search box and closes the suggestions.
Am I missing something?

**Comment by mancze** [comment]
I think it depends on how google rolls out updates. I guess you are getting the old version where it worked. I can reproduce this issue in both Firefox and Chrome. Today I see even another update to google search - the searchbox has rounded borders now.

![image](https://user-images.githubusercontent.com/1493286/49362967-a1a74000-f6e0-11e8-96e0-17ee7ff7d847.png)

**Comment by tedzhu** [comment]
Thanks for looking into and fixing this. I agree that google's change is not rolled out at once, when I created the issue it's already round cornered for me
